/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RpiPinReader */

#ifndef _Included_RpiPinReader
#define _Included_RpiPinReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RpiPinReader
 * Method:    readPins
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_RpiPinReader_readPins
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
